spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts-dev
    username: postgres
    password: simoQB24188
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
